# image:
#   file: .gitpod.Dockerfile

tasks:
  - init: pnpm i
    command: pnpm dev

ports:
  - port: 3000
    visibility: public
  - port: 8000
    visibility: public

vscode:
  extensions:
    - firsttris.vscode-jest-runner
