# image:
#   file: .gitpod.Dockerfile

tasks:
  - init: pnpm i
    command: pnpm dev
  - init: echo 'export PATH=/usr/local/bin:/home/gitpod/.jsvu/bin:$PATH' >> ~/.bashrc && npm i -g jsvu && yes | jsvu || true && source ~/.bashrc

ports:
  - port: 3000
    visibility: public
  - port: 8000
    visibility: public

vscode:
  extensions:
    - firsttris.vscode-jest-runner
