image:
  file: .gitpod.Dockerfile

tasks:
  - init: pnpm i
    command: pnpm dev

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - firsttris.vscode-jest-runner
